apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - ingestion-service.yaml
  - query-service.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: enterprise-rag
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
    includeTemplates: true
